/**
 * TODO BottomSheetDialog按钮参数类
 * author: 桃花镇童长老ᥫ᭡
 * since: 2024/08/18
 * 仓库主页：https://ohpm.openharmony.cn/#/cn/detail/@pura%2Fharmony-dialog
 * github: https://github.com/787107497
 * gitee: https://gitee.com/tongyuyan/harmony-utils
 * CSDN: https://blog.csdn.net/qq_32922545
 * QQ交流群: 569512366
 */
export class SheetOptions {
  value: ResourceStr = ''; //按钮的内容。
  fontColor?: ResourceColor; //按钮的字体颜色。
  fontSize?: number | string | Resource; //按钮的文字大小，，默认16。
}
