import { BaseInputOptions } from './base/BaseInputOptions';

/**
 * TODO 输入弹出框，参数类
 * author: 桃花镇童长老ᥫ᭡
 * since: 2024/08/18
 * 仓库主页：https://ohpm.openharmony.cn/#/cn/detail/@pura%2Fharmony-dialog
 * github: https://github.com/787107497
 * gitee: https://gitee.com/tongyuyan/harmony-utils
 * CSDN: https://blog.csdn.net/qq_32922545
 * QQ交流群: 569512366
 */
export interface TextInputOptions extends BaseInputOptions {

  inputType?: InputType; //输入框类型。默认值：InputType.Normal

}