/**
 * 类型约束
 * author: 桃花镇童长老ᥫ᭡
 * since: 2024/07/01
 * 仓库主页：https://ohpm.openharmony.cn/#/cn/detail/@pura%2Fharmony-utils
 * github: https://github.com/787107497
 * gitee: https://gitee.com/tongyuyan/harmony-utils
 * CSDN: https://blog.csdn.net/qq_32922545
 * QQ交流群: 569512366
 */
export declare namespace crypto {

  type BhuCoding = 'base64' | 'hex' | 'utf8' | 'utf-8';
  type BhCoding = 'base64' | 'hex';

  type SHA = 'SHA1' | 'SHA224' | 'SHA256' | 'SHA384' | 'SHA512';

}